### ISSUE TITLE
Handle compression

### ISSUE THREAD

**Issue by inkihh** [RaJiska/JAPM#4]
Hi RaJiska,

first of all, I love JAPM. It help a lot.

Now I can't extract a pbo, and I suspect that it's compressed. In the sources I see "TODO: Handle compression". Is this something you will add at some point?

Thanks,
inkihh

**Comment by RaJiska** [comment]
Heya Inkihh!

Currently this tool handles the most common form of compression. However there seems to be a few of them and unfortunately algorithms are not open source. I believe this is mostly done in an attempt to avoid people reverse engineering PBO mission files of servers by users.

Unfortunately this would require a lot of effort to be able reverse engineers the algorithms, which I am not ready to provide at the moment. But if you know somebody who feel like doing it or if you have the time to I'd be happy to accept your Pull Request.

**Comment by inkihh** [comment]
I think it's LZSS compression, and the algorithm is basically explained [here](https://community.bistudio.com/wiki/PBO_File_Format#Operation_Flashpoint:_Elite_PBO). I'd love to create a pull request, but I can't code C ;-)

**Comment by RaJiska** [comment]
> I think it's LZSS compression, and the algorithm is basically explained [here](https://community.bistudio.com/wiki/PBO_File_Format#Operation_Flashpoint:_Elite_PBO). I'd love to create a pull request, but I can't code C ;-)

From what I remember this algorithm doesn't apply to Arma 3. A derived version of it which took me much longer to crack than I'd like to admit seems to be used and which you can find [here](https://github.com/RaJiska/JAPM/blob/master/src/pbo/pbo_decompress.c).

The page you referenced is what I initially based myself on to work on this project but proved to be largely incomplete back them. I see some changes have been made since then though, but as you can see it doesn't even reflect the algorithm that is proven to work in the code I provided just above.

Getting back into it would require me to invest too much time than I can afford unfortunately. Feel free to fork or reimplement in a code you are comfortable with if you have the time! I'd be happy to know that the code I wrote few years back is still useful to some :)
